// ═══════════════════════════════════════════════════════════
// 파이썬 예제 — 브라우저(Skulpt)에서 바로 돌아가는 것만 둔다
// ═══════════════════════════════════════════════════════════
// turtle: true 인 예제는 실행하면 "그림" 탭이 열린다.

window.CODELAB_EXAMPLES = [
  {
    id: 'hello', label: '인사하기',
    code: [
      '# Hello World!',
      'print("안녕하세요!")',
      'print("파이썬에 오신 것을 환영해요!")',
    ].join('\n'),
  },
  {
    id: 'input', label: '입력 받기',
    code: [
      '# 입력(input) 예제',
      'name = input("이름을 입력하세요: ")',
      'age = input("나이를 입력하세요: ")',
      'print(name + "님, 안녕하세요!")',
      'print("내년에는 " + str(int(age) + 1) + "살이 되시네요!")',
    ].join('\n'),
  },
  {
    id: 'loop', label: '구구단 (반복문)',
    code: [
      '# 구구단 출력',
      'for i in range(1, 10):',
      '    for j in range(1, 10):',
      '        v = i * j',
      '        if v < 10:',
      '            v = " " + str(v)',
      '        else:',
      '            v = str(v)',
      '        print(str(i) + " x " + str(j) + " = " + v, end="  ")',
      '    print()',
    ].join('\n'),
  },
  {
    id: 'function', label: '함수 만들기',
    code: [
      '# 함수 예제',
      'def greet(name, count=3):',
      '    for i in range(count):',
      '        print(str(i + 1) + "번째 인사: 안녕, " + name + "!")',
      '',
      'greet("파이썬")',
      'print("---")',
      'greet("코딩", 2)',
    ].join('\n'),
  },
  {
    id: 'list', label: '리스트',
    code: [
      '# 리스트 예제',
      'fruits = ["사과", "바나나", "체리", "딸기", "포도"]',
      '',
      'print("== 과일 목록 ==")',
      'for i in range(len(fruits)):',
      '    print("  " + str(i + 1) + ". " + fruits[i])',
      '',
      'print("")',
      'print("총 " + str(len(fruits)) + "개의 과일이 있습니다.")',
      'print("첫 번째: " + fruits[0])',
      'print("마지막: " + fruits[-1])',
      '',
      '# 리스트 컴프리헨션',
      'long_fruits = [x for x in fruits if len(x) >= 2]',
      'print("")',
      'print("2글자 이상 과일: " + str(long_fruits))',
    ].join('\n'),
  },
  {
    id: 'turtle', label: '로봇 그림 — 도형', turtle: true,
    code: [
      '# 로봇 그래픽 - 다각형',
      'import turtle',
      '',
      't = turtle.Turtle()',
      't.shape("robot")',
      't.speed(8)',
      't.penup()',
      't.goto(-200, 0)',
      't.pendown()',
      'colors = ["red", "blue", "green", "orange", "purple", "cyan"]',
      '',
      'for i in range(6):',
      '    t.pencolor(colors[i])',
      '    t.pensize(3)',
      '    sides = i + 3',
      '    for j in range(sides):',
      '        t.forward(20)',
      '        t.left(360 / sides)',
      '    t.penup()',
      '    t.forward(60)',
      '    t.pendown()',
    ].join('\n'),
  },
  {
    id: 'turtle2', label: '로봇 그림 — 나선', turtle: true,
    code: [
      '# 로봇 그래픽 - 컬러 나선',
      'import turtle',
      '',
      't = turtle.Turtle()',
      't.shape("robot")',
      't.speed(0)',
      '',
      'for i in range(200):',
      '    r = i * 255 // 200',
      '    g = (200 - i) * 255 // 200',
      '    b = 128',
      '    t.pencolor(r / 255.0, g / 255.0, b / 255.0)',
      '    t.pensize(max(1, i // 40))',
      '    t.forward(i * 0.8)',
      '    t.left(59)',
    ].join('\n'),
  },
  {
    id: 'game', label: '숫자 맞추기 게임',
    code: [
      '# 숫자 맞추기 게임',
      'import random',
      '',
      'print("=== 숫자 맞추기 게임 ===")',
      'print("1부터 20 사이의 숫자를 맞춰보세요!")',
      'print("")',
      '',
      'answer = random.randint(1, 20)',
      'tries = 0',
      '',
      'while True:',
      '    tries = tries + 1',
      '    guess = int(input("[" + str(tries) + "번째 시도] 숫자: "))',
      '',
      '    if guess < answer:',
      '        print("  >> 더 큰 숫자입니다!")',
      '    elif guess > answer:',
      '        print("  >> 더 작은 숫자입니다!")',
      '    else:',
      '        print("")',
      '        print("정답! " + str(tries) + "번 만에 맞추셨습니다!")',
      '        break',
    ].join('\n'),
  },
];
